# Generated by Django 4.1.5 on 2023-02-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_discipline_group_remove_student_college_mark_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студента'},
        ),
        migrations.RemoveField(
            model_name='mark',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='discipline',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='discipline',
            field=models.CharField(max_length=50, verbose_name='Название дисциплины'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.CharField(max_length=50, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.CharField(choices=[('н', 'н'), ('2', 2), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tree.student', verbose_name='Имя студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='Возраст студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tree.group', verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя студента'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата получения оценки')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tree.discipline', verbose_name='Название Дисциплины')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tree.group', verbose_name='Название Урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.AddField(
            model_name='mark',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tree.lesson', verbose_name='Имя урока'),
        ),
    ]
