# Generated by Django 4.1.5 on 2023-02-10 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_alter_discipline_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tree.group', verbose_name='Название Группы'),
        ),
    ]
